// Automatically generated by MockGen. DO NOT EDIT!
// Source: cmd/marathon-resource/marathon.go

package mocks

import (
	http "net/http"

	gomock "github.com/golang/mock/gomock"
)

// Mock of doer interface
type Mockdoer struct {
	ctrl     *gomock.Controller
	recorder *_MockdoerRecorder
}

// Recorder for Mockdoer (not exported)
type _MockdoerRecorder struct {
	mock *Mockdoer
}

func NewMockdoer(ctrl *gomock.Controller) *Mockdoer {
	mock := &Mockdoer{ctrl: ctrl}
	mock.recorder = &_MockdoerRecorder{mock}
	return mock
}

func (_m *Mockdoer) EXPECT() *_MockdoerRecorder {
	return _m.recorder
}

func (_m *Mockdoer) Do(req *http.Request) (*http.Response, error) {
	ret := _m.ctrl.Call(_m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockdoerRecorder) Do(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Do", arg0)
}
